### PR TITLE
fix: replace node EventEmitter with EventEmitter3

### PR DESCRIPTION
**Pull request by henri-hulski**
Fixes cerebral/cerebral#389.

### CODE REVIEW

**Comment by Guria** [comment]
Test failed unfortunately :(

**Comment by henri-hulski** [comment]
@Guria 2 tests are failing :
- 'should not allow going to a new url'
- 'should handle trailing slash convertion'

I tried to look into it, but really no idea, why these 2 are failing and the others are passing. 

Maybe you can have a look.

**Comment by henri-hulski** [comment]
The test error outputs are not very helpful. They even don't show the actual value of the assertions.

**Comment by christianalfoni** [comment]
So much for "drop in replacement" as stated on their repo ;-)

Does this problem happen every time? It is not a race condition that just happened to work on last test run?

**Comment by christianalfoni** [comment]
Yeah, now suddenly one of them ran green. It seems to be race condition not related to event emitter. Have to investigate this locally I think... I have my hands full with tutorial right now, can look into it tomorrow I think

**Comment by Guria** [comment]
Ahh forgot about this issue with addressbar. Restarted a test. I had a plans on addressbar refactoring :)

**Comment by Guria** [comment]
Have to restart it about 5 times :)

**Pull request merged**
