### PR TITLE
reduce size of lib substantially by switching to url-parse instead of urijs

### PR DESCRIPTION
**Pull request by jdeal**
I love this lib, but the size is kind of out of control for pulling into my project, even compared to a fairly chunky lib like `history`. The main problem is the dependency on `urijs`. This could be eliminated almost completely with some custom parsing, but in this PR, I just switched to `url-parse` instead of `urijs`, which is nearly a drop-in replacement.

This reduces the total size of the gizipped `addressbar` by about 77%.

With `urijs`:

``` plain
Uncompressed: ~106.63 kB
Uglified: 46.33 kB
Uglified + gzipped (level: default): ~14.51 kB
```

With `url-parse`:

``` plain
Uncompressed: ~24.68 kB
Uglified: 9.05 kB
Uglified + gzipped (level: default): ~3.23 kB
```

This brings it well under the full `history` lib which gzips to ~7.32 kB and even under the more minimal `history/lib/createBrowserHistory` which gzips to ~4.63 kB.

### CODE REVIEW

**Comment by Guria** [comment]
Thanks for great contribution. I'll test it now and release it asap

**Comment by Guria** [comment]
Published. Thanks for your contribution

**Comment by jdeal** [comment]
Awesome! Thanks for merging!

**Comment by bryanhelmig** [comment]
:+1: :-D

**Comment by christianalfoni** [comment]
Awesome stuff, thanks @jdeal :-D

**Pull request merged**
